name = "my-app"
main = "src/index.ts"
compatibility_date = "2024-12-18"

 compatibility_flags = [ "nodejs_compat" ]

# uncomment this part and paste the acc url
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTE1YzFjNzctOGQwMC00NWVlLTgyZTAtNGVlZjQ1MjQxYjVlIiwidGVuYW50X2lkIjoiYjhjMjExMDA1MjMyZTliMWJkZTA0YzQwNjBjYzU4NjY5YWFkOTJiZjMyNWFmY2IyYmI4YmMwY2NkNmYzYzI1OCIsImludGVybmFsX3NlY3JldCI6IjMzYzdmZDhlLWFlNjctNDc5Yi05ODhjLWI3NmQzNmQ0MzRiZSJ9.Xpv3239fDzWWzTzbV-yunzregwhLQDZsDS87MoUvJTc"
JWT_SECRET="my_secret_password"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1